FROM ubuntu as builder
RUN apt-get update
RUN apt-get install -y golang
RUN apt-get install -y git
RUN apt-get install -y libsystemd-dev
ENV GOPATH /root/go
WORKDIR $GOPATH/src/github.com/box/kube-iptables-tailer
COPY . $GOPATH/src/github.com/box/kube-iptables-tailer
RUN make build-cgo

FROM ubuntu
LABEL maintainer="Saifuding Diliyaer <sdiliyaer@box.com>"
WORKDIR /root/
COPY --from=builder /root/go/src/github.com/box/kube-iptables-tailer/kube-iptables-tailer /kube-iptables-tailer
