---
  apiVersion: "apps/v1"
  kind: "DaemonSet"
  metadata: 
    name: "kube-iptables-tailer"
    namespace: "kube-system"
  spec: 
    selector:
      matchLabels:
        app: "kube-iptables-tailer"
    template:
      metadata:
        labels:
          app: "kube-iptables-tailer"
      spec:
        serviceAccount: kube-iptables-tailer
        containers: 
          - name: "kube-iptables-tailer"
            command:
              - "/kube-iptables-tailer"
            env:
              - name: LOG_LEVEL
                value: info
              - name: "IPTABLES_LOG_PATH"
                value: "/var/log/iptables.log"
              - name: "IPTABLES_LOG_PREFIX"
                # log prefix defined in your iptables chains
                value: "calico-drop:"
            image: "boxinc/kube-iptables-tailer:v0.1.0"
            volumeMounts: 
              - name: "iptables-logs"
                mountPath: "/var/log"
                readOnly: true
        volumes:
          - name: "iptables-logs"
            hostPath: 
              # absolute path of the directory containing iptables log file on your host
              path: "/var/log"

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: kube-iptables-tailer
  namespace: kube-system

---

kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kube-iptables-tailer
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["v1"]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]

---

kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kube-iptables-tailer
subjects:
  - kind: ServiceAccount
    name: kube-iptables-tailer
    namespace: kube-system
roleRef:
  kind: ClusterRole
  name: kube-iptables-tailer
  apiGroup: rbac.authorization.k8s.io
